#######################################################################################################
###----------------------------------------- VACUUM CLEANER ----------------------------------------###
#######################################################################################################
- alias: Vacuum Cleaner - Start
  trigger:
    platform: state
    entity_id: sensor.location_daniel
    from: 'Home'
    to: 'Away'
  condition:
    condition: and
    conditions:
    - condition: time
      before: '17:00:00'
    - condition: template
      value_template: '{{ as_timestamp(now()) - as_timestamp(states.automation.vacuum_cleaner_start.attributes.last_triggered) | int > 129600 }}'
  action:
  - service: vacuum.start
    entity_id: vacuum.xiaomi_vacuum_cleaner
    
- alias: Vacuum Cleaner - Stop
  trigger:
    platform: state
    entity_id: sensor.location_daniel
    to: 'Home'
  action:
  - service: vacuum.return_to_base
    entity_id: vacuum.xiaomi_vacuum_cleaner


#######################################################################################################
###---------------------------------------- WASHING MACHINE ----------------------------------------###
#######################################################################################################

- alias: Washing Machine - Running
  trigger:
    - platform: numeric_state
      entity_id: sensor.washing_machine_power
      above: 10
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: sensor.washing_machine_status
        state: Idle
      - condition: state
        entity_id: sensor.washing_machine_status
        state: Clean
      - condition: state
        entity_id: sensor.washing_machine_status
        state: Finishing
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.washing_machine_status
        option: Running


- alias: Washing Machine - Finishing
  trigger:
    - platform: numeric_state
      entity_id: sensor.washing_machine_power
      below: 3
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sensor.washing_machine_status
        state: Running
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.washing_machine_status
        option: Finishing


- alias: Washing Machine - Clean
  trigger:
    - platform: state
      entity_id: sensor.washing_machine_status
      to: Finishing
      for:
        seconds: 45
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sensor.washing_machine_status
        state: Finishing
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.washing_machine_status
        option: Clean

- alias: Washing Machine - Turn Off
  trigger:
    - platform: state
      entity_id: binary_sensor.door_window_washing_machine
      to: 'on'
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: sensor.washing_machine_status
        state: Finishing
      - condition: state
        entity_id: sensor.washing_machine_status
        state: Clean
  action:
    - service: homeassistant.turn_off
      data:
        entity_id: switch.plug_washing_machine

- alias: Washing Machine - Idle
  trigger:
    - platform: state
      entity_id: binary_sensor.door_window_washing_machine
      to: 'on'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.washing_machine_status
        option: Idle 

- alias: Washing Machine - Turn On
  trigger:
    - platform: state
      entity_id: binary_sensor.door_window_washing_machine
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sensor.washing_machine_status
        state: Idle
      - condition: state
        entity_id: switch.plug_washing_machine
        state: 'off'
  action:
    - service: homeassistant.turn_on
      data:
        entity_id: switch.plug_washing_machine

#######################################################################################################
###------------------------------------------- DISHWASHER ------------------------------------------###
#######################################################################################################

- alias: Dishwasher - Running
  trigger:
    - platform: numeric_state
      entity_id: sensor.dishwasher_power
      above: 5
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: sensor.dishwasher_status
        state: Idle
      - condition: state
        entity_id: sensor.dishwasher_status
        state: Clean
      - condition: state
        entity_id: sensor.dishwasher_status
        state: Finishing
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.dishwasher_status
        option: Running

- alias: Dishwasher - Finishing
  trigger:
    - platform: numeric_state
      entity_id: sensor.dishwasher_power
      below: 5
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sensor.dishwasher_status
        state: Running
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.dishwasher_status
        option: Finishing

- alias: Dishwasher - Clean
  trigger:
    - platform: state
      entity_id: sensor.dishwasher_status
      to: Finishing
      for:
        minutes: 2
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sensor.dishwasher_status
        state: Finishing
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.dishwasher_status
        option: Clean

- alias: Dishwasher - Idle
  trigger:
    - platform: state
      entity_id: binary_sensor.door_window_sensor_xxx
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sensor.dishwasher_status
        state: Clean
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.dishwasher_status
        option: Idle 
    - service: homeassistant.turn_off
      data:
        entity_id: switch.plug_dishwasher


- alias: Diwshwasher - Turn on
  trigger:
    - platform: state
      entity_id: binary_sensor.door_window_sensor_xxx
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sensor.dishwasher_status
        state: Idle
      - condition: state
        entity_id: switch.plug_dishwasher
        state: 'off'
  action:
    - service: homeassistant.turn_on
      data:
        entity_id: switch.plug_dishwasher


- alias: Fan Ensuite - On
  trigger:
    platform: numeric_state
    entity_id: sensor.humidity_ensuite
    above: 75
  action:
    service: homeassistant.turn_on
    entity_id: fan.ensuite

- alias: Fan Ensuite - Off
  trigger:
    platform: numeric_state
    entity_id: sensor.humidity_ensuite
    below: 75
  action:
    service: homeassistant.turn_off
    entity_id: fan.ensuite

