#######################################################################################################
###---------------------------------------- PANEL AUTOMATIONS --------------------------------------###
#######################################################################################################
##### LIGHTS
- alias: Tablet Panel Lights Detail On
  trigger:
    platform: state
    entity_id: input_select.tablet_panel_detail
    to: "Lights"
  action:
  - service: homeassistant.turn_on
    entity_id: input_boolean.tile_tablet_button_lights

- alias: Tablet Panel Lights Detail Off
  trigger:
    platform: state
    entity_id: input_select.tablet_panel_detail
    from: "Lights"
  action:
  - service: homeassistant.turn_off
    entity_id: input_boolean.tile_tablet_button_lights

##### LIGHTS ADVANCED
- alias: Tablet Panel Lights Advanced Detail On
  trigger:
    platform: state
    entity_id: input_select.tablet_panel_detail
    to: "Lights Advanced"
  action:
  - service: homeassistant.turn_on
    entity_id: input_boolean.tile_tablet_button_lights_advanced

- alias: Tablet Panel Lights Advanced Detail Off
  trigger:
    platform: state
    entity_id: input_select.tablet_panel_detail
    from: "Lights Advanced"
  action:
  - service: homeassistant.turn_off
    entity_id: input_boolean.tile_tablet_button_lights_advanced

- alias: Tablet Panel Lights Advanced Timeout
  trigger:
  - platform: state
    entity_id: input_select.tablet_panel_detail
    to: "Lights Advanced"
    for:
      seconds: 45
  action:
  - service: input_select.select_option
    entity_id: input_select.tablet_panel_detail
    data:
      option: "Lights"
  - service: homeassistant.turn_off
    entity_id: input_boolean.tile_tablet_button_lights_advanced


##### MEDIA
- alias: Tablet Panel Media Detail On
  trigger:
    platform: state
    entity_id: input_select.tablet_panel_detail
    to: "Media"
  action:
  - service: homeassistant.turn_on
    entity_id: input_boolean.tile_tablet_button_media

- alias: Tablet Panel Media Detail Off
  trigger:
    platform: state
    entity_id: input_select.tablet_panel_detail
    from: "Media"
  action:
  - service: homeassistant.turn_off
    entity_id: input_boolean.tile_tablet_button_media

##### CAMERA
- alias: Tablet Panel Camera Detail On
  trigger:
    platform: state
    entity_id: input_select.tablet_panel_detail
    to: "Cameras"
  action:
  - service: homeassistant.turn_on
    entity_id: input_boolean.tile_tablet_button_cameras

- alias: Tablet Panel Camera Detail Off
  trigger:
    platform: state
    entity_id: input_select.tablet_panel_detail
    from: "Cameras"
  action:
  - service: homeassistant.turn_off
    entity_id: input_boolean.tile_tablet_button_cameras

##### SPRINKLERS
- alias: Tablet Panel Sprinklers On
  trigger:
    platform: state
    entity_id: input_select.tablet_panel_detail
    to: "Sprinklers"
  action:
  - service: homeassistant.turn_on
    entity_id: input_boolean.tile_tablet_button_sprinklers

- alias: Tablet Panel Sprinklers Off
  trigger:
    platform: state
    entity_id: input_select.tablet_panel_detail
    from: "Sprinklers"
  action:
  - service: homeassistant.turn_off
    entity_id: input_boolean.tile_tablet_button_sprinklers

##### SPRINKLERS ADVANCED
- alias: Tablet Panel Sprinklers Advanced On
  trigger:
    platform: state
    entity_id: input_select.tablet_panel_detail
    to: "Sprinklers Advanced"
  action:
  - service: homeassistant.turn_on
    entity_id: input_boolean.tile_tablet_button_sprinklers_advanced

- alias: Tablet Panel Sprinklers Advanced Off
  trigger:
  - platform: state
    entity_id: input_select.tablet_panel_detail
    from: "Sprinklers Advanced"
  action:
  - service: homeassistant.turn_off
    entity_id: input_boolean.tile_tablet_button_sprinklers_advanced

- alias: Tablet Panel Sprinklers Advanced Timeout
  trigger:
  - platform: state
    entity_id: input_select.tablet_panel_detail
    to: "Sprinklers Advanced"
    for:
      seconds: 45
  action:
  - service: input_select.select_option
    entity_id: input_select.tablet_panel_detail
    data:
      option: "Sprinklers"

##### WASHER
- alias: Tablet Panel Washer On
  trigger:
    platform: state
    entity_id: input_select.tablet_panel_detail
    to: "Washer"
  action:
  - service: homeassistant.turn_on
    entity_id: input_boolean.tile_tablet_button_washer

- alias: Tablet Panel Washer Off
  trigger:
    platform: state
    entity_id: input_select.tablet_panel_detail
    from: "Washer"
  action:
  - service: homeassistant.turn_off
    entity_id: input_boolean.tile_tablet_button_washer

##### DISHWASHER
- alias: Tablet Panel Dishwasher On
  trigger:
    platform: state
    entity_id: input_select.tablet_panel_detail
    to: "Dishwasher"
  action:
  - service: homeassistant.turn_on
    entity_id: input_boolean.tile_tablet_button_dishwasher

- alias: Tablet Panel Dishwasher Off
  trigger:
    platform: state
    entity_id: input_select.tablet_panel_detail
    from: "Dishwasher"
  action:
  - service: homeassistant.turn_off
    entity_id: input_boolean.tile_tablet_button_dishwasher

##### ALARM CLOCK
- alias: Tablet Panel Alarm Clock On
  trigger:
    platform: state
    entity_id: input_select.tablet_panel_detail
    to: "Alarm Clock"
  action:
  - service: homeassistant.turn_on
    entity_id: input_boolean.tile_tablet_button_alarm_clock

- alias: Tablet Panel Alarm Clock Off
  trigger:
    platform: state
    entity_id: input_select.tablet_panel_detail
    from: "Alarm Clock"
  action:
  - service: homeassistant.turn_off
    entity_id: input_boolean.tile_tablet_button_alarm_clock

##### VACUUM CLEANER
- alias: Tablet Panel Vacuum Cleaner On
  trigger:
    platform: state
    entity_id: input_select.tablet_panel_detail
    to: "Vacuum Cleaner"
  action:
  - service: homeassistant.turn_on
    entity_id: input_boolean.tile_tablet_button_vacuum_cleaner

- alias: Tablet Panel Vacuum Cleaner Off
  trigger:
    platform: state
    entity_id: input_select.tablet_panel_detail
    from: "Vacuum Cleaner"
  action:
  - service: homeassistant.turn_off
    entity_id: input_boolean.tile_tablet_button_vacuum_cleaner

##### SHED
- alias: Tablet Panel Shed On
  trigger:
    platform: state
    entity_id: input_select.tablet_panel_detail
    to: "Shed"
  action:
  - service: homeassistant.turn_on
    entity_id: input_boolean.tile_tablet_button_shed

- alias: Tablet Panel Shed Off
  trigger:
    platform: state
    entity_id: input_select.tablet_panel_detail
    from: "Shed"
  action:
  - service: homeassistant.turn_off
    entity_id: input_boolean.tile_tablet_button_shed

##### WEATHER
- alias: Tablet Panel Weather On
  trigger:
    platform: state
    entity_id: input_select.tablet_panel_detail
    to: "Weather"
  action:
  - service: homeassistant.turn_on
    entity_id: input_boolean.tile_tablet_button_weather

- alias: Tablet Panel Weather Off
  trigger:
    platform: state
    entity_id: input_select.tablet_panel_detail
    from: "Weather"
  action:
  - service: homeassistant.turn_off
    entity_id: input_boolean.tile_tablet_button_weather

##### MOTION
- alias: Tablet Panel Motion On
  trigger:
    platform: state
    entity_id: input_select.tablet_panel_detail
    to: "Motion"
  action:
  - service: homeassistant.turn_on
    entity_id: input_boolean.tile_tablet_button_motion

- alias: Tablet Panel Motion Off
  trigger:
    platform: state
    entity_id: input_select.tablet_panel_detail
    from: "Motion"
  action:
  - service: homeassistant.turn_off
    entity_id: input_boolean.tile_tablet_button_motion

##### ROOMS
- alias: Tablet Panel Rooms On
  trigger:
    platform: state
    entity_id: input_select.tablet_panel_detail
    to: "Rooms"
  action:
  - service: homeassistant.turn_on
    entity_id: input_boolean.tile_tablet_button_rooms

- alias: Tablet Panel Rooms Off
  trigger:
    platform: state
    entity_id: input_select.tablet_panel_detail
    from: "Rooms"
  action:
  - service: homeassistant.turn_off
    entity_id: input_boolean.tile_tablet_button_rooms

##### TEMPERATURE
- alias: Tablet Panel Temperature On
  trigger:
    platform: state
    entity_id: input_select.tablet_panel_detail
    to: "Temperature"
  action:
  - service: homeassistant.turn_on
    entity_id: input_boolean.tile_tablet_button_temperature

- alias: Tablet Panel Temperature Off
  trigger:
    platform: state
    entity_id: input_select.tablet_panel_detail
    from: "Temperature"
  action:
  - service: homeassistant.turn_off
    entity_id: input_boolean.tile_tablet_button_temperature

##### AC
- alias: Tablet Panel AC On
  trigger:
    platform: state
    entity_id: input_select.tablet_panel_detail
    to: "Air Conditioner"
  action:
  - service: homeassistant.turn_on
    entity_id: input_boolean.tile_tablet_button_ac

- alias: Tablet Panel AC Off
  trigger:
    platform: state
    entity_id: input_select.tablet_panel_detail
    from: "Air Conditioner"
  action:
  - service: homeassistant.turn_off
    entity_id: input_boolean.tile_tablet_button_ac

##### APPLIANCES
- alias: Tablet Panel Appliances On
  trigger:
    platform: state
    entity_id: input_select.tablet_panel_detail
    to: "Appliances"
  action:
  - service: homeassistant.turn_on
    entity_id: input_boolean.tile_tablet_button_appliances

- alias: Tablet Panel Appliances Off
  trigger:
    platform: state
    entity_id: input_select.tablet_panel_detail
    from: "Appliances"
  action:
  - service: homeassistant.turn_off
    entity_id: input_boolean.tile_tablet_button_appliances

- alias: Tablet Panel Appliances Washing Machine On
  trigger:
    platform: state
    entity_id: input_select.tablet_panel_detail_appliances
    to: "Washing Machine"
  action:
  - service: homeassistant.turn_on
    entity_id: input_boolean.tile_tablet_button_appliances_washing_machine

- alias: Tablet Panel Appliances Washing Machine Off
  trigger:
    platform: state
    entity_id: input_select.tablet_panel_detail_appliances
    from: "Washing Machine"
  action:
  - service: homeassistant.turn_off
    entity_id: input_boolean.tile_tablet_button_appliances_washing_machine

- alias: Tablet Panel Appliances Dishwasher On
  trigger:
    platform: state
    entity_id: input_select.tablet_panel_detail_appliances
    to: "Dishwasher"
  action:
  - service: homeassistant.turn_on
    entity_id: input_boolean.tile_tablet_button_appliances_dishwasher

- alias: Tablet Panel Appliances Dishwasher Off
  trigger:
    platform: state
    entity_id: input_select.tablet_panel_detail_appliances
    from: "Dishwasher"
  action:
  - service: homeassistant.turn_off
    entity_id: input_boolean.tile_tablet_button_appliances_dishwasher

- alias: Tablet Panel Appliances Vacuum Cleaner On
  trigger:
    platform: state
    entity_id: input_select.tablet_panel_detail_appliances
    to: "Vacuum Cleaner"
  action:
  - service: homeassistant.turn_on
    entity_id: input_boolean.tile_tablet_button_appliances_vacuum_cleaner

- alias: Tablet Panel Appliances Vacuum Cleaner Off
  trigger:
    platform: state
    entity_id: input_select.tablet_panel_detail_appliances
    from: "Vacuum Cleaner"
  action:
  - service: homeassistant.turn_off
    entity_id: input_boolean.tile_tablet_button_appliances_vacuum_cleaner

