#######################################################################################################
###---------------------------------------- PANEL AUTOMATIONS --------------------------------------###
#######################################################################################################
##### Covers
- alias: Tablet Panel Covers Detail On
  trigger:
    platform: state
    entity_id: input_select.tablet_panel_detail
    to: "Covers"
  action:
  - service: homeassistant.turn_on
    entity_id: input_boolean.tablet_button_covers

- alias: Tablet Panel Covers Detail Off
  trigger:
    platform: state
    entity_id: input_select.tablet_panel_detail
    from: "Covers"
  action:
  - service: homeassistant.turn_off
    entity_id: input_boolean.tablet_button_covers

##### LIGHTS
- alias: Tablet Panel Lights Detail On
  trigger:
    platform: state
    entity_id: input_select.tablet_panel_detail
    to: "Lights"
  action:
  - service: homeassistant.turn_on
    entity_id: input_boolean.tablet_button_lights

- alias: Tablet Panel Lights Detail Off
  trigger:
    platform: state
    entity_id: input_select.tablet_panel_detail
    from: "Lights"
  action:
  - service: homeassistant.turn_off
    entity_id: input_boolean.tablet_button_lights

##### MEDIA
- alias: Tablet Panel Media Detail On
  trigger:
    platform: state
    entity_id: input_select.tablet_panel_detail
    to: "Media"
  action:
  - service: homeassistant.turn_on
    entity_id: input_boolean.tablet_button_media

- alias: Tablet Panel Media Detail Off
  trigger:
    platform: state
    entity_id: input_select.tablet_panel_detail
    from: "Media"
  action:
  - service: homeassistant.turn_off
    entity_id: input_boolean.tablet_button_media

##### CAMERA
- alias: Tablet Panel Camera Detail On
  trigger:
    platform: state
    entity_id: input_select.tablet_panel_detail
    to: "Cameras"
  action:
  - service: homeassistant.turn_on
    entity_id: input_boolean.tablet_button_cameras

- alias: Tablet Panel Camera Detail Off
  trigger:
    platform: state
    entity_id: input_select.tablet_panel_detail
    from: "Cameras"
  action:
  - service: homeassistant.turn_off
    entity_id: input_boolean.tablet_button_cameras

##### SPRINKLERS
- alias: Tablet Panel Sprinklers On
  trigger:
    platform: state
    entity_id: input_select.tablet_panel_detail
    to: "Sprinklers"
  action:
  - service: homeassistant.turn_on
    entity_id: input_boolean.tablet_button_sprinklers

- alias: Tablet Panel Sprinklers Off
  trigger:
    platform: state
    entity_id: input_select.tablet_panel_detail
    from: "Sprinklers"
  action:
  - service: homeassistant.turn_off
    entity_id: input_boolean.tablet_button_sprinklers



##### ALARM CLOCK
- alias: Tablet Panel Alarm Clock On
  trigger:
    platform: state
    entity_id: input_select.tablet_panel_detail
    to: "Alarm Clock"
  action:
  - service: homeassistant.turn_on
    entity_id: input_boolean.tablet_button_alarm_clock

- alias: Tablet Panel Alarm Clock Off
  trigger:
    platform: state
    entity_id: input_select.tablet_panel_detail
    from: "Alarm Clock"
  action:
  - service: homeassistant.turn_off
    entity_id: input_boolean.tablet_button_alarm_clock



##### WEATHER
- alias: Tablet Panel Weather On
  trigger:
    platform: state
    entity_id: input_select.tablet_panel_detail
    to: "Weather"
  action:
  - service: homeassistant.turn_on
    entity_id: input_boolean.tablet_button_weather

- alias: Tablet Panel Weather Off
  trigger:
    platform: state
    entity_id: input_select.tablet_panel_detail
    from: "Weather"
  action:
  - service: homeassistant.turn_off
    entity_id: input_boolean.tablet_button_weather

##### MOTION
- alias: Tablet Panel Motion On
  trigger:
    platform: state
    entity_id: input_select.tablet_panel_detail
    to: "Motion"
  action:
  - service: homeassistant.turn_on
    entity_id: input_boolean.tablet_button_motion

- alias: Tablet Panel Motion Off
  trigger:
    platform: state
    entity_id: input_select.tablet_panel_detail
    from: "Motion"
  action:
  - service: homeassistant.turn_off
    entity_id: input_boolean.tablet_button_motion


##### TEMPERATURE
- alias: Tablet Panel Temperature On
  trigger:
    platform: state
    entity_id: input_select.tablet_panel_detail
    to: "Temperature"
  action:
  - service: homeassistant.turn_on
    entity_id: input_boolean.tablet_button_temperature

- alias: Tablet Panel Temperature Off
  trigger:
    platform: state
    entity_id: input_select.tablet_panel_detail
    from: "Temperature"
  action:
  - service: homeassistant.turn_off
    entity_id: input_boolean.tablet_button_temperature

##### AC
- alias: Tablet Panel AC On
  trigger:
    platform: state
    entity_id: input_select.tablet_panel_detail
    to: "Air Conditioner"
  action:
  - service: homeassistant.turn_on
    entity_id: input_boolean.tablet_button_ac

- alias: Tablet Panel AC Off
  trigger:
    platform: state
    entity_id: input_select.tablet_panel_detail
    from: "Air Conditioner"
  action:
  - service: homeassistant.turn_off
    entity_id: input_boolean.tablet_button_ac

##### APPLIANCES
- alias: Tablet Panel Appliances On
  trigger:
    platform: state
    entity_id: input_select.tablet_panel_detail
    to: "Appliances"
  action:
  - service: homeassistant.turn_on
    entity_id: input_boolean.tablet_button_appliances

- alias: Tablet Panel Appliances Off
  trigger:
    platform: state
    entity_id: input_select.tablet_panel_detail
    from: "Appliances"
  action:
  - service: homeassistant.turn_off
    entity_id: input_boolean.tablet_button_appliances

- alias: Tablet Panel Appliances Washing Machine On
  trigger:
    platform: state
    entity_id: input_select.tablet_panel_detail_appliances
    to: "Washing Machine"
  action:
  - service: homeassistant.turn_on
    entity_id: input_boolean.tablet_button_appliances_washing_machine

- alias: Tablet Panel Appliances Washing Machine Off
  trigger:
    platform: state
    entity_id: input_select.tablet_panel_detail_appliances
    from: "Washing Machine"
  action:
  - service: homeassistant.turn_off
    entity_id: input_boolean.tablet_button_appliances_washing_machine

- alias: Tablet Panel Appliances Dishwasher On
  trigger:
    platform: state
    entity_id: input_select.tablet_panel_detail_appliances
    to: "Dishwasher"
  action:
  - service: homeassistant.turn_on
    entity_id: input_boolean.tablet_button_appliances_dishwasher

- alias: Tablet Panel Appliances Dishwasher Off
  trigger:
    platform: state
    entity_id: input_select.tablet_panel_detail_appliances
    from: "Dishwasher"
  action:
  - service: homeassistant.turn_off
    entity_id: input_boolean.tablet_button_appliances_dishwasher

- alias: Tablet Panel Appliances Vacuum Cleaner On
  trigger:
    platform: state
    entity_id: input_select.tablet_panel_detail_appliances
    to: "Vacuum Cleaner"
  action:
  - service: homeassistant.turn_on
    entity_id: input_boolean.tablet_button_appliances_vacuum_cleaner

- alias: Tablet Panel Appliances Vacuum Cleaner Off
  trigger:
    platform: state
    entity_id: input_select.tablet_panel_detail_appliances
    from: "Vacuum Cleaner"
  action:
  - service: homeassistant.turn_off
    entity_id: input_boolean.tablet_button_appliances_vacuum_cleaner

