#######################################################################################################
###------------------------------------- IRRIGATION AUTOMATIONS ------------------------------------###
#######################################################################################################

- alias: Sprinklers - Zone 1 On
  trigger:
  - platform: state
    entity_id: timer.sprinkler_zone_1
    to: 'active'
  action:
  - service: homeassistant.turn_on
    entity_id: switch.sprinkler_zone_1

- alias: Sprinklers - Zone 1 Off
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.sprinkler_zone_1
  - platform: state
    entity_id: switch.sprinkler_zone_1
    to: 'off'
  action:
  - service: homeassistant.turn_off
    entity_id: switch.sprinkler_zone_1
  - service: timer.finish
    entity_id: timer.sprinkler_zone_1

- alias: Sprinklers - Zone 2 On
  trigger:
  - platform: state
    entity_id: timer.sprinkler_zone_2
    to: 'active'
  action:
  - service: homeassistant.turn_on
    entity_id: switch.sprinkler_zone_2

- alias: Sprinklers - Zone 2 Off
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.sprinkler_zone_2
  action:
  - service: homeassistant.turn_off
    entity_id: switch.sprinkler_zone_2

- alias: Sprinklers - Zone 3 On
  trigger:
  - platform: state
    entity_id: timer.sprinkler_zone_3
    to: 'active'
  action:
  - service: homeassistant.turn_on
    entity_id: switch.sprinkler_zone_3

- alias: Sprinklers - Zone 3 Off
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.sprinkler_zone_3
  action:
  - service: homeassistant.turn_off
    entity_id: switch.sprinkler_zone_3

- alias: Sprinklers - Zone 4 On
  trigger:
  - platform: state
    entity_id: timer.sprinkler_zone_4
    to: 'active'
  action:
  - service: homeassistant.turn_on
    entity_id: switch.sprinkler_zone_4

- alias: Sprinklers - Zone 4 Off
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.sprinkler_zone_4
  action:
  - service: homeassistant.turn_off
    entity_id: switch.sprinkler_zone_4


- alias: Sprinklers - Turn on
  trigger: 
    platform: sun
    event: sunrise
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: '{{( states.input_number.irrigation_tracker.state | float) < 0 }}'
#      - condition: numeric_state
#        entity_id: sensor.pws_precip_1d_mm
#        below: 2
  action:
    service: homeassistant.turn_on
    entity_id: input_boolean.sprinkler_control

- alias: Sprinklers - Control On
  trigger:
    platform: state
    entity_id: input_boolean.sprinkler_control
    to: 'on'
  action:
    service: script.sprinklers

- alias: Sprinklers - Control Off
  trigger:
    platform: state
    entity_id: input_boolean.sprinkler_control
    to: 'off'
  action:
  - service: homeassistant.turn_off
    entity_id:
    - group.irrigation
    - script.sprinklers
  - service: timer.finish
    entity_id:
    - timer.sprinkler_zone_1
    - timer.sprinkler_zone_2
    - timer.sprinkler_zone_3
    - timer.sprinkler_zone_4


- alias: Irrigation - Calculate Stuff
  trigger: 
    platform: time
    at: '23:59:00'
  action:
    - service: input_number.set_value
      data_template:
        entity_id: input_number.irrigation_tracker
        value: >
            {% if (states.sensor.dark_sky_daytime_high_apparent_temperature_0d.state | float) >= (states.input_number.irrigation_temp_hot.state | float) %}
              {{ (states.input_number.irrigation_tracker.state | float)
                - (states.input_number.irrigation_scalar_hot.state | float) * (states.input_number.irrigation_week_base.state | float) / 7 
                + (states.sensor.bom_rain_today.state | float)
                + (states.input_number.irrigation_rate.state | float) * (states.sensor.irrigation_duration_today.state | float)
              }}
            {% elif (states.sensor.dark_sky_daytime_high_apparent_temperature_0d.state | float) >= (states.input_number.irrigation_temp_warm.state | float) %}
              {{ (states.input_number.irrigation_tracker.state | float)
                - (states.input_number.irrigation_scalar_warm.state | float) * (states.input_number.irrigation_week_base.state | float) / 7 
                + (states.sensor.bom_rain_today.state | float)
                + (states.input_number.irrigation_rate.state | float) * (states.sensor.irrigation_duration_today.state | float)
              }}
            {% else %}
              {{ (states.input_number.irrigation_tracker.state | float)
                - (states.input_number.irrigation_week_base.state | float) / 7
                + (states.sensor.bom_rain_today.state | float)
                + (states.input_number.irrigation_rate.state | float) * (states.sensor.irrigation_duration_today.state | float)
              }}
            {% endif %}
    - service: input_number.set_value
      data_template:
        entity_id: input_number.rain_today_midnight
        value: "{{ states.sensor.bom_rain_today.state | float }}"


# rain today from BOM doesn't reset at midnight, need to account for rain between midnight and just before the sprinklers might turn on
- alias: Irrigation - Calculate tracker midnight to sunrise
  trigger: 
    platform: sun
    event: sunrise
    offset: "-00:00:01"
  action:
    - service: input_number.set_value
      data_template:
        entity_id: input_number.irrigation_tracker
        value: >
              {{ (states.input_number.irrigation_tracker.state | float)
                + (states.sensor.bom_rain_today.state | float)
                - (states.input_number.rain_today_midnight.state | float)
              }}
    - service: input_number.set_value
      data_template:
        entity_id: input_number.rain_today_sunrise
        value: "{{ states.sensor.bom_rain_today.state | float }}"

## because BOM update 'Rain Today' just after 9am each day
- alias: Irrigation - Calculate tracker sunrise to 9am
  trigger: 
    platform: time
    at: '09:00:00'
  action:
    - service: input_number.set_value
      data_template:
        entity_id: input_number.irrigation_tracker
        value: >
              {{ (states.input_number.irrigation_tracker.state | float)
                + (states.sensor.bom_rain_today.state | float)
                - (states.input_number.rain_today_sunrise.state | float)
              }}
    - service: input_number.set_value
      data:
        entity_id: input_number.rain_today_sunrise
        value: 0
    - service: input_number.set_value
      data:
        entity_id: input_number.rain_today_midnight
        value: 0
