#######################################################################################################
###--------------------------------------- MOTION AUTOMATIONS --------------------------------------###
#######################################################################################################

# WARDROBE ############################################################################################
- alias: Motion Detect - Wardrobe
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_wardrobe
    to: 'on'
  action:
  - service: homeassistant.turn_on
    entity_id: light.wardrobe
    data_template:
      transition: 2
#      brightness_pct: '{{states.input_number.dynamic_light_brightness.state}}'

- alias: Motion Clear - Wardrobe
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_wardrobe
    to: 'off'
  action:
    service: homeassistant.turn_off
    entity_id: light.wardrobe
    data:
      transition: 5

# LAUNDRY #############################################################################################
- alias: Motion Detect - Laundry
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_laundry
    to: 'on'
  condition:
    condition: state
    entity_id: input_boolean.light_check
    state: 'on'
  action:
  - service: homeassistant.turn_on
    entity_id: light.laundry
    data_template:
      transition: 2
#      brightness_pct: '{{states.input_number.dynamic_light_brightness.state}}'
  - service: input_select.select_option
    data:
      entity_id: input_select.room_tracker
      option: Laundry

- alias: Motion Clear - Laundry
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_laundry
    to: 'off'
  condition:
    condition: state
    entity_id: input_boolean.light_check
    state: 'on'
  action:
    service: homeassistant.turn_off
    entity_id: light.laundry
    data:
      transition: 5

# BEDROOM #############################################################################################
- alias: Motion Detect - Bedroom
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_bedroom
    to: 'on'
  condition:
    condition: state
    entity_id: input_boolean.light_check
    state: 'on'
  action:
  - service: homeassistant.turn_on
    entity_id: light.bedroom
    data_template:
      transition: 2
#      brightness_pct: '{{states.input_number.dynamic_light_brightness.state}}'

- alias: Motion Clear - Bedroom
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_bedroom
    to: 'off'
    for:
      minutes: 5
  condition:
    condition: state
    entity_id: input_boolean.light_check
    state: 'on'
  action:
    service: homeassistant.turn_off
    entity_id: light.bedroom
    data:
      transition: 5

# ENSUITE #############################################################################################
- alias: Motion Detect - Ensuite
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_ensuite
    from: 'off'
    to: 'on'
  action:
  - service: homeassistant.turn_on
    entity_id: light.ensuite
    data_template:
      transition: 2
#      brightness_pct: '{{states.input_number.dynamic_light_brightness.state}}'

- alias: Motion Clear - Ensuite (No Shower)
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_ensuite
    to: 'off'
    for:
      minutes: 2
  condition:
    condition: numeric_state
    entity_id: sensor.humidity_158d0001f52bfc
    below: 75
  action:
    service: homeassistant.turn_off
    entity_id: light.ensuite
    data:
      transition: 5

- alias: Motion Clear - Ensuite (Shower)
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_ensuite
    to: 'off'
    for:
      minutes: 20
  condition:
    condition: numeric_state
    entity_id: sensor.humidity_158d0001f52bfc
    above: 75
  action:
    service: homeassistant.turn_off
    entity_id: light.ensuite
    data:
      transition: 5

# STUDY #############################################################################################
- alias: Motion Detect - Study
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_study
    to: 'on'
  condition:
    condition: state
    entity_id: input_boolean.light_check
    state: 'on'
  action:
  - service: homeassistant.turn_on
    entity_id: light.study
    data:
      transition: 2

- alias: Motion Clear - Study
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_study
    to: 'off'
    for:
      minutes: 10
  condition:
    condition: state
    entity_id: input_boolean.light_check
    state: 'on'
  action:
    service: homeassistant.turn_off
    entity_id: light.study
    data:
      transition: 5

# LIVING ROOM #############################################################################################
- alias: Motion Detect - Living Room
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_living_room
    to: 'on'
  condition:
    condition: state
    entity_id: input_boolean.light_check
    state: 'on'
  action:
  - service: homeassistant.turn_on
    entity_id: light.living_room
    data:
      transition: 2

- alias: Motion Clear - Living Room
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_living_room
    to: 'off'
    for:
      minutes: 30
  condition:
    condition: state
    entity_id: input_boolean.light_check
    state: 'on'
  action:
    service: homeassistant.turn_off
    entity_id: light.living_room
    data:
      transition: 5


# KITCHEN #############################################################################################
- alias: Motion Detect - Kitchen
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_kitchen
    to: 'on'
  condition:
    condition: state
    entity_id: input_boolean.light_check
    state: 'on'
  action:
  - service: homeassistant.turn_on
    entity_id: light.kitchen
    data_template:
      transition: 2
#      brightness_pct: '{{states.input_number.dynamic_light_brightness.state}}'

- alias: Motion Clear - Kitchen
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_kitchen
    to: 'off'
    for:
      minutes: 5
  condition:
    condition: state
    entity_id: input_boolean.light_check
    state: 'on'
  action:
    service: homeassistant.turn_off
    entity_id: light.kitchen
    data:
      transition: 5

# Lounge #############################################################################################
- alias: Motion Detect - Lounge
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_lounge
    to: 'on'
  condition:
    condition: state
    entity_id: input_boolean.light_check
    state: 'on'
  action:
  - service: homeassistant.turn_on
    entity_id: light.lounge
    data_template:
      transition: 2
#      brightness_pct: '{{states.input_number.dynamic_light_brightness.state}}'

- alias: Motion Clear - Lounge
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_lounge
    to: 'off'
    for:
      minutes: 5
  condition:
    condition: state
    entity_id: input_boolean.light_check
    state: 'on'
  action:
    service: homeassistant.turn_off
    entity_id: light.lounge
    data:
      transition: 5

# BACK DOOR #############################################################################################
- alias: Motion Detect - Back Door
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_back_door
    to: 'on'
  condition:
    condition: state
    entity_id: input_boolean.light_check
    state: 'on'
  action:
  - service: homeassistant.turn_on
    entity_id: light.back_door
    data_template:
      transition: 2
#      brightness_pct: '{{states.input_number.dynamic_light_brightness.state}}'

- alias: Motion Clear - Back Door
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_back_door
    to: 'off'
    for:
      minutes: 0
  condition:
    condition: state
    entity_id: input_boolean.light_check
    state: 'on'
  action:
    service: homeassistant.turn_off
    entity_id: light.back_door
    data:
      transition: 5

# CARPORT #############################################################################################
- alias: Motion Detect - Carport
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_carport
    to: 'on'
  condition:
    condition: state
    entity_id: input_boolean.light_check
    state: 'on'
  action:
  - service: homeassistant.turn_on
    entity_id: light.carport
    data_template:
      transition: 2
#      brightness_pct: '{{states.input_number.dynamic_light_brightness.state}}'

- alias: Motion Clear - Carport
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_carport
    to: 'off'
    for:
      minutes: 0
  condition:
    condition: state
    entity_id: input_boolean.light_check
    state: 'on'
  action:
    service: homeassistant.turn_off
    entity_id: light.carport
    data:
      transition: 5

# FRONT DOOR #############################################################################################
- alias: Motion Detect - Front Door
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_front_door
    to: 'on'
  condition:
    condition: state
    entity_id: input_boolean.light_check
    state: 'on'
  action:
  - service: homeassistant.turn_on
    entity_id: light.front_door
    data_template:
      transition: 2
#      brightness_pct: '{{states.input_number.dynamic_light_brightness.state}}'

- alias: Motion Clear - Front Door
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_front_door
    to: 'off'
    for:
      minutes: 0
  condition:
    condition: state
    entity_id: input_boolean.light_check
    state: 'on'
  action:
    service: homeassistant.turn_off
    entity_id: light.front_door
    data:
      transition: 5

# FRONT DOOR TABLET #############################################################################################
- alias: Motion Detect - Front Door - Tablet
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_front_door
    to: 'on'
  action:
  - service: mqtt.publish
    data:
      topic: "tablet/1"
      payload: "on"

- alias: Motion Clear - Front Door - Tablet
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_front_door
    from: 'on'
    to: 'off'
  action:
    - service: mqtt.publish
      data:
        topic: "tablet/1"
        payload: "off"

# OUTSIDE FRONT #############################################################################################
- alias: Motion Detect - Outside Front
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_outside_front
    to: 'on'
  condition:
    condition: state
    entity_id: input_boolean.light_check
    state: 'on'
  action:
  - service: homeassistant.turn_on
    entity_id: light.outside_front
    data_template:
      transition: 2
      brightness_pct: '{{states.input_number.dynamic_light_brightness.state}}'

- alias: Motion Clear - Outside Front
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_outside_front
    to: 'off'
    for:
      minutes: 0
  condition:
    condition: state
    entity_id: input_boolean.light_check
    state: 'on'
  action:
    service: homeassistant.turn_off
    entity_id: light.outside_front
    data:
      transition: 5


#######################################################################################################
###----------------------------------- ROOM TRACKER AUTOMATIONS ------------------------------------###
#######################################################################################################

- alias: Room Tracker Leave - Bedroom
  trigger:
    platform: state
    entity_id: input_select.room_tracker
    from: "Bedroom"
#    for:
#      minutes: 0
#  condition:
#    condition: state
#    entity_id: group.room_tracker_motion_bedroom_all
#    state: 'off'
  action:
  - wait_template: "{{ is_state('group.room_tracker_motion_bedroom_all', 'off') }}"
    timeout: '00:05:00'
  - service: homeassistant.turn_off
    entity_id:
    - light.bedroom
    - light.ensuite
    - light.wardrobe
    data:
      transition: 4

- alias: Room Tracker Leave - Study
  trigger:
    platform: state
    entity_id: input_select.room_tracker
    from: "Study"
#    for:
#      minutes: 0
  condition:
    condition: state
    entity_id: binary_sensor.motion_sensor_study
    state: 'off'
  action:
  - service: homeassistant.turn_off
    entity_id:
    - light.study
    data:
      transition: 4

- alias: Room Tracker Leave - Living Room
  trigger:
    platform: state
    entity_id: input_select.room_tracker
    from: "Living Room"
#    for:
#      minutes: 0
  condition:
    condition: state
    entity_id: group.room_tracker_motion_living_room_all
    state: 'off'
  action:
  - service: homeassistant.turn_off
    entity_id:
    - light.living_room
    - light.lounge
    - light.kitchen
    data:
      transition: 4

- alias: Room Tracker Leave - Laundry
  trigger:
    platform: state
    entity_id: input_select.room_tracker
    from: "Laundry"
#    for:
#      minutes: 0
  condition:
    condition: state
    entity_id: binary_sensor.motion_sensor_laundry
    state: 'off'
  action:
  - service: homeassistant.turn_off
    entity_id:
    - light.laundry
    data:
      transition: 4

- alias: Room Tracker Leave - Carport
  trigger:
    platform: state
    entity_id: input_select.room_tracker
    from: "Carport"
#    for:
#      minutes: 0
  condition:
    condition: state
    entity_id: binary_sensor.motion_sensor_carport
    state: 'off'
  action:
  - service: homeassistant.turn_off
    entity_id:
    - light.carport
    data:
      transition: 4

#- alias: Room Tracker - Bedroom
#  trigger:
#    platform: state
#    entity_id: input_select.room_tracker
#    to: "Bedroom"
#    for:
#      minutes: 2
#  action:
#  - service: homeassistant.turn_off
#    entity_id:
#    - group.lights_outside
#    - light.living_room
#    - light.study
#    - light.front_door
#    - light.kitchen
#    - light.lounge
#    - light.laundry
#    data:
#      transition: 4

#- alias: Room Tracker - Study
#  trigger:
#    platform: state
#    entity_id: input_select.room_tracker
#    to: "Study"
#    for:
#      minutes: 2
#  action:
#  - service: homeassistant.turn_off
#    entity_id:
#    - group.lights_outside
#    - light.living_room
#    - light.bedroom
#    - light.wardrobe
#    - light.ensuite
#    - light.front_door
#    - light.kitchen
#    - light.lounge
#    - light.laundry
#    data:
#      transition: 4

#- alias: Room Tracker - Living Room
#  trigger:
#    platform: state
#    entity_id: input_select.room_tracker
#    to: "Living Room"
#    for:
#      minutes: 2
#  action:
#  - service: homeassistant.turn_off
#    entity_id:
#    - group.lights_outside
#    - light.study
#    - light.bedroom
#    - light.wardrobe
#    - light.ensuite
#    - light.front_door
#    - light.laundry
#    data:
#      transition: 4

- alias: Room Tracker Motion Detect - Bedroom
  trigger:
    platform: state
    entity_id: group.room_tracker_motion_bedroom_all
    to: 'on'
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.room_tracker
      option: Bedroom

- alias: Room Tracker Motion Clear - Bedroom
  trigger:
    platform: state
    entity_id: group.room_tracker_motion_bedroom_all
    to: 'off'
  condition:
    condition: state
    entity_id: input_select.room_tracker
    state: 'Bedroom'
  action:
  - service: input_select.select_option
    data_template:
      entity_id: input_select.room_tracker
      option: >-
        {% if is_state('group.room_tracker_motion_living_room_all', 'on') %}
          Living Room
        {% elif is_state('binary_sensor.motion_sensor_study', 'on') %}
          Study
        {% elif is_state('binary_sensor.motion_sensor_laundry', 'on') %}
          Laundry
        {% elif is_state('binary_sensor.motion_sensor_carport', 'on') %}
          Carport
        {% elif is_state('group.room_tracker_motion_bedroom_all', 'on') %}
          Bedroom
        {% else %}
          Bedroom
        {% endif %}


- alias: Room Tracker Motion Detect - Study
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_study
    to: 'on'
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.room_tracker
      option: Study

- alias: Room Tracker Motion Clear - Study
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_study
    to: 'off'
  condition:
    condition: state
    entity_id: input_select.room_tracker
    state: 'Study'
  action:
  - service: input_select.select_option
    data_template:
      entity_id: input_select.room_tracker
      option: >-
        {% if is_state('group.room_tracker_motion_living_room_all', 'on') %}
          Living Room
        {% elif is_state('binary_sensor.motion_sensor_study', 'on') %}
          Study
        {% elif is_state('binary_sensor.motion_sensor_laundry', 'on') %}
          Laundry
        {% elif is_state('binary_sensor.motion_sensor_carport', 'on') %}
          Carport
        {% elif is_state('group.room_tracker_motion_bedroom_all', 'on') %}
          Bedroom
        {% else %}
          Study
        {% endif %}

- alias: Room Tracker Motion Detect - Living Room
  trigger:
    platform: state
    entity_id: group.room_tracker_motion_living_room_all
    to: 'on'
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.room_tracker
      option: Living Room

- alias: Room Tracker Motion Clear - Living Room
  trigger:
    platform: state
    entity_id: group.room_tracker_motion_living_room_all
    to: 'off'
  condition:
    condition: state
    entity_id: input_select.room_tracker
    state: 'Living Room'
  action:
  - service: input_select.select_option
    data_template:
      entity_id: input_select.room_tracker
      option: >-
        {% if is_state('group.room_tracker_motion_living_room_all', 'on') %}
          Living Room
        {% elif is_state('binary_sensor.motion_sensor_study', 'on') %}
          Study
        {% elif is_state('binary_sensor.motion_sensor_laundry', 'on') %}
          Laundry
        {% elif is_state('binary_sensor.motion_sensor_carport', 'on') %}
          Carport
        {% elif is_state('group.room_tracker_motion_bedroom_all', 'on') %}
          Bedroom
        {% else %}
          Living Room
        {% endif %}
