#######################################################################################################
###--------------------------------------- LIGHT AUTOMATIONS ---------------------------------------###
#######################################################################################################

# LIGHT CHECK #########################################################################################
- alias: Light Check Sunset
  trigger:
    platform: sun
    event: sunset
    offset: "-00:30:00"
  action:
    service: homeassistant.turn_on
    entity_id: input_boolean.light_check

- alias: Light Check Sunrise
  trigger:
    platform: sun
    event: sunrise
  action: 
    service: homeassistant.turn_off
    entity_id: input_boolean.light_check
    
- alias: Light Check Startup
  trigger: 
    platform: homeassistant
    event: start
  condition:
    condition: or
    conditions:
    - condition: sun
      after: sunset
      after_offset: "-00:30:00"
    - condition: sun
      before: sunrise
  action:
    service: homeassistant.turn_on
    entity_id: input_boolean.light_check


# LIGHT CONTROL #######################################################################################
- alias: Lights - Arrival 
  trigger:
    platform: state
    entity_id: sensor.location_daniel
    to: 'Home'
  condition:
    condition: state
    entity_id: input_boolean.light_check
    state: 'on'
  action:
    service: homeassistant.turn_on
    entity_id:
      - group.welcome_lights
      - light.living_room
    data:
      transition: 5

- alias: Lights - Sunset
  trigger:
    platform: sun
    event: sunset
    offset: "-00:30:00"
  condition:
    condition: state
    entity_id: sensor.location_daniel
    state: 'Home'
  action:
    service: homeassistant.turn_on
    entity_id: light.living_room
    data:
      transition: 90

- alias: Lights - Turn off Welcome Lights
  trigger:
    platform: state
    entity_id: group.welcome_control_lights
    from: 'off'
    to: 'on'
  action:
    service: homeassistant.turn_off
    entity_id: group.welcome_lights
    data:
      transition: 5

- alias: Lights - Roller Door Opening
  trigger:
    platform: state
    entity_id: cover.roller_door
    from: 'closed'
    to: 'open'
  condition:
    condition: state
    entity_id: input_boolean.light_check
    state: 'on'
  action:
  - service: homeassistant.turn_on
    entity_id: light.back_door
    data:
      transition: 2
  - service: homeassistant.turn_on
    entity_id: light.carport


# LIGHT BRIGHTNESS #######################################################################################
- alias: Lights Dynamic Brightness Reset
  trigger:
    platform: sun
    event: sunrise
  action:
    service: input_number.set_value
    data:
      entity_id: input_number.dynamic_light_brightness
      value: 100
 

- alias: Lights Dynamic Brightness 10 PM
  trigger:
    platform: time
    at: '22:00:00'
  action:
    service: input_number.set_value
    data:
      entity_id: input_number.dynamic_light_brightness
      value: 75

- alias: Lights Dynamic Brightness 11 PM
  trigger:
    platform: time
    at: '23:00:00'
  action:
    service: input_number.set_value
    data:
      entity_id: input_number.dynamic_light_brightness
      value: 50

- alias: Lights Dynamic Brightness 12 AM
  trigger:
    platform: time
    at: '00:00:00'
  action:
    service: input_number.set_value
    data:
      entity_id: input_number.dynamic_light_brightness
      value: 30

- alias: Lights Dynamic Brightness 1 AM
  trigger:
    platform: time
    at: '01:00:00'
  action:
    service: input_number.set_value
    data:
      entity_id: input_number.dynamic_light_brightness
      value: 20

- alias: Lights Dynamic Brightness 2 AM
  trigger:
    platform: time
    at: '01:00:00'
  action:
    service: input_number.set_value
    data:
      entity_id: input_number.dynamic_light_brightness
      value: 10

# LIFX SET #######################################################################################
- alias: Lights Set LIFX Colour and Brightness
  trigger:
  - platform: state
    entity_id: input_number.light_temp
  - platform: state
    entity_id: input_number.dynamic_light_brightness
  action:
    service: light.lifx_set_state
    data:
      transition: 5
    data_template:
      kelvin: '{{states.input_number.light_temp.state | int}}'
      brightness_pct: '{{states.input_number.dynamic_light_brightness.state}}'      

# LIGHT COLOUR #######################################################################################
- alias: Lights Set Light Colour Temp
  trigger:
    platform: state
    entity_id: light.flux
  action:
    service: input_number.set_value
    data:
      entity_id: input_number.light_temp
    data_template:
      value: '{{( 1000000 / states.light.flux.attributes.color_temp ) | int}}'