#######################################################################################################
###---------------------------------------- PANEL AUTOMATIONS --------------------------------------###
#######################################################################################################
##### LIGHTS
- alias: Tablet Lights Detail Panel On
  trigger:
    platform: state
    entity_id: input_select.tablet_panel_detail
    to: "Lights"
  action:
  - service: group.set_visibility
    entity_id: group.tile_tablet_panel_lights
    data:
      visible: True
  - service: homeassistant.turn_on
    entity_id: input_boolean.tile_tablet_button_lights

- alias: Tablet Lights Detail Panel Off
  trigger:
    platform: state
    entity_id: input_select.tablet_panel_detail
    from: "Lights"
  action:
  - service: group.set_visibility
    entity_id: group.tile_tablet_panel_lights
    data:
      visible: False
  - service: homeassistant.turn_off
    entity_id: input_boolean.tile_tablet_button_lights

##### LIGHTS ADVANCED
- alias: Tablet Lights Advanced Detail Panel On
  trigger:
    platform: state
    entity_id: input_select.tablet_panel_detail
    to: "Lights Advanced"
  action:
  - service: group.set_visibility
    entity_id: group.tile_tablet_panel_lights_advanced
    data:
      visible: True
  - service: homeassistant.turn_on
    entity_id: input_boolean.tile_tablet_button_lights_advanced

- alias: Tablet Lights Advanced Detail Panel Off
  trigger:
    platform: state
    entity_id: input_select.tablet_panel_detail
    from: "Lights Advanced"
  action:
  - service: group.set_visibility
    entity_id: group.tile_tablet_panel_lights_advanced
    data:
      visible: False
  - service: homeassistant.turn_off
    entity_id: input_boolean.tile_tablet_button_lights_advanced

- alias: Tablet Lights Advanced Panel Timeout
  trigger:
  - platform: state
    entity_id: input_select.tablet_panel_detail
    to: "Lights Advanced"
    for:
      seconds: 45
  action:
  - service: input_select.select_option
    entity_id: input_select.tablet_panel_detail
    data:
      option: "Lights"
  - service: homeassistant.turn_off
    entity_id: input_boolean.tile_tablet_button_lights_advanced


##### MEDIA
- alias: Tablet Media Detail Panel On
  trigger:
    platform: state
    entity_id: input_select.tablet_panel_detail
    to: "Media"
  action:
  - service: group.set_visibility
    entity_id: group.tile_tablet_panel_media
    data:
      visible: True
  - service: homeassistant.turn_on
    entity_id: input_boolean.tile_tablet_button_media

- alias: Tablet Media Detail Panel Off
  trigger:
    platform: state
    entity_id: input_select.tablet_panel_detail
    from: "Media"
  action:
  - service: group.set_visibility
    entity_id: group.tile_tablet_panel_media
    data:
      visible: False
  - service: homeassistant.turn_off
    entity_id: input_boolean.tile_tablet_button_media

##### CAMERA
- alias: Tablet Camera Detail Panel On
  trigger:
    platform: state
    entity_id: input_select.tablet_panel_detail
    to: "Cameras"
  action:
  - service: group.set_visibility
    entity_id: group.tile_tablet_panel_cameras
    data:
      visible: True
  - service: homeassistant.turn_on
    entity_id: input_boolean.tile_tablet_button_cameras

- alias: Tablet Camera Detail Panel Off
  trigger:
    platform: state
    entity_id: input_select.tablet_panel_detail
    from: "Cameras"
  action:
  - service: group.set_visibility
    entity_id: group.tile_tablet_panel_cameras
    data:
      visible: False
  - service: homeassistant.turn_off
    entity_id: input_boolean.tile_tablet_button_cameras

##### SPRINKLERS
- alias: Tablet Sprinklers Panel On
  trigger:
    platform: state
    entity_id: input_select.tablet_panel_detail
    to: "Sprinklers"
  action:
  - service: group.set_visibility
    entity_id: group.tile_tablet_panel_sprinklers
    data:
      visible: True
  - service: homeassistant.turn_on
    entity_id: input_boolean.tile_tablet_button_sprinklers

- alias: Tablet Sprinklers Panel Off
  trigger:
    platform: state
    entity_id: input_select.tablet_panel_detail
    from: "Sprinklers"
  action:
  - service: group.set_visibility
    entity_id: group.tile_tablet_panel_sprinklers
    data:
      visible: False
  - service: homeassistant.turn_off
    entity_id: input_boolean.tile_tablet_button_sprinklers

##### SPRINKLERS ADVANED
- alias: Tablet Sprinklers Advanced Panel On
  trigger:
    platform: state
    entity_id: input_select.tablet_panel_detail
    to: "Sprinklers Advanced"
  action:
  - service: group.set_visibility
    entity_id: group.tile_tablet_panel_sprinklers_advanced
    data:
      visible: True
  - service: homeassistant.turn_on
    entity_id: input_boolean.tile_tablet_button_sprinklers_advanced

- alias: Tablet Sprinklers Advanced Panel Off
  trigger:
  - platform: state
    entity_id: input_select.tablet_panel_detail
    from: "Sprinklers Advanced"
  action:
  - service: group.set_visibility
    entity_id: group.tile_tablet_panel_sprinklers_advanced
    data:
      visible: False
  - service: homeassistant.turn_off
    entity_id: input_boolean.tile_tablet_button_sprinklers_advanced

- alias: Tablet Sprinklers Advanced Panel Timeout
  trigger:
  - platform: state
    entity_id: input_select.tablet_panel_detail
    to: "Sprinklers Advanced"
    for:
      seconds: 45
  action:
  - service: input_select.select_option
    entity_id: input_select.tablet_panel_detail
    data:
      option: "Sprinklers"

##### WASHER
- alias: Tablet Washer Panel On
  trigger:
    platform: state
    entity_id: input_select.tablet_panel_detail
    to: "Washer"
  action:
  - service: group.set_visibility
    entity_id: group.tile_tablet_panel_washer
    data:
      visible: True
  - service: homeassistant.turn_on
    entity_id: input_boolean.tile_tablet_button_washer

- alias: Tablet Washer Panel Off
  trigger:
    platform: state
    entity_id: input_select.tablet_panel_detail
    from: "Washer"
  action:
  - service: group.set_visibility
    entity_id: group.tile_tablet_panel_washer
    data:
      visible: False
  - service: homeassistant.turn_off
    entity_id: input_boolean.tile_tablet_button_washer

##### DISHWASHER
- alias: Tablet Dishwasher Panel On
  trigger:
    platform: state
    entity_id: input_select.tablet_panel_detail
    to: "Dishwasher"
  action:
  - service: group.set_visibility
    entity_id: group.tile_tablet_panel_dishwasher
    data:
      visible: True
  - service: homeassistant.turn_on
    entity_id: input_boolean.tile_tablet_button_dishwasher

- alias: Tablet Dishwasher Panel Off
  trigger:
    platform: state
    entity_id: input_select.tablet_panel_detail
    from: "Dishwasher"
  action:
  - service: group.set_visibility
    entity_id: group.tile_tablet_panel_dishwasher
    data:
      visible: False
  - service: homeassistant.turn_off
    entity_id: input_boolean.tile_tablet_button_dishwasher

##### ALARM CLOCK
- alias: Tablet Alarm Clock Panel On
  trigger:
    platform: state
    entity_id: input_select.tablet_panel_detail
    to: "Alarm Clock"
  action:
  - service: group.set_visibility
    entity_id: group.tile_tablet_panel_alarm_clock
    data:
      visible: True
  - service: homeassistant.turn_on
    entity_id: input_boolean.tile_tablet_button_alarm_clock

- alias: Tablet Alarm Clock Panel Off
  trigger:
    platform: state
    entity_id: input_select.tablet_panel_detail
    from: "Alarm Clock"
  action:
  - service: group.set_visibility
    entity_id: group.tile_tablet_panel_alarm_clock
    data:
      visible: False
  - service: homeassistant.turn_off
    entity_id: input_boolean.tile_tablet_button_alarm_clock

##### VACUUM CLEANER
- alias: Tablet Vacuum Cleaner Panel On
  trigger:
    platform: state
    entity_id: input_select.tablet_panel_detail
    to: "Vacuum Cleaner"
  action:
  - service: group.set_visibility
    entity_id: group.tile_tablet_panel_vacuum_cleaner
    data:
      visible: True
  - service: homeassistant.turn_on
    entity_id: input_boolean.tile_tablet_button_vacuum_cleaner

- alias: Tablet Vacuum Cleaner Panel Off
  trigger:
    platform: state
    entity_id: input_select.tablet_panel_detail
    from: "Vacuum Cleaner"
  action:
  - service: group.set_visibility
    entity_id: group.tile_tablet_panel_vacuum_cleaner
    data:
      visible: False
  - service: homeassistant.turn_off
    entity_id: input_boolean.tile_tablet_button_vacuum_cleaner

##### SHED
- alias: Tablet Shed Panel On
  trigger:
    platform: state
    entity_id: input_select.tablet_panel_detail
    to: "Shed"
  action:
  - service: group.set_visibility
    entity_id: group.tile_tablet_panel_shed
    data:
      visible: True
  - service: homeassistant.turn_on
    entity_id: input_boolean.tile_tablet_button_shed

- alias: Tablet Shed Panel Off
  trigger:
    platform: state
    entity_id: input_select.tablet_panel_detail
    from: "Shed"
  action:
  - service: group.set_visibility
    entity_id: group.tile_tablet_panel_shed
    data:
      visible: False
  - service: homeassistant.turn_off
    entity_id: input_boolean.tile_tablet_button_shed

##### WEATHER
- alias: Tablet Weather Panel On
  trigger:
    platform: state
    entity_id: input_select.tablet_panel_detail
    to: "Weather"
  action:
  - service: group.set_visibility
    entity_id: group.tile_tablet_panel_weather
    data:
      visible: True
  - service: homeassistant.turn_on
    entity_id: input_boolean.tile_tablet_button_weather

- alias: Tablet Weather Panel Off
  trigger:
    platform: state
    entity_id: input_select.tablet_panel_detail
    from: "Weather"
  action:
  - service: group.set_visibility
    entity_id: group.tile_tablet_panel_weather
    data:
      visible: False
  - service: homeassistant.turn_off
    entity_id: input_boolean.tile_tablet_button_weather

##### MOTION
- alias: Tablet Motion Panel On
  trigger:
    platform: state
    entity_id: input_select.tablet_panel_detail
    to: "Motion"
  action:
  - service: group.set_visibility
    entity_id: group.tile_tablet_panel_motion
    data:
      visible: True
  - service: homeassistant.turn_on
    entity_id: input_boolean.tile_tablet_button_motion

- alias: Tablet Motion Panel Off
  trigger:
    platform: state
    entity_id: input_select.tablet_panel_detail
    from: "Motion"
  action:
  - service: group.set_visibility
    entity_id: group.tile_tablet_panel_motion
    data:
      visible: False
  - service: homeassistant.turn_off
    entity_id: input_boolean.tile_tablet_button_motion

